<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>SimpleCaptcha</Title>
        <Authors>Pascal Pomper</Authors>
        <Description>A simple .NET library that generates CAPTCHA images. </Description>
        <Copyright>2025 Pascal Pomper</Copyright>
        <PackageProjectUrl>https://github.com/Pasi4K5/simple-captche</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/Pasi4K5/simple-captche/blob/main/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/Pasi4K5/simple-captche</RepositoryUrl>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
      <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\*.ttf" />
    </ItemGroup>

</Project>
