<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>SimpleCaptchaDotNet</PackageId>
        <Title>SimpleCaptchaDotNet</Title>
        <Authors>Pascal Pomper</Authors>
        <Description>A simple .NET library that generates CAPTCHA images. </Description>
        <Copyright>2025 Pascal Pomper</Copyright>
        <PackageProjectUrl>https://github.com/Pasi4K5/simple-captcha-dot-net</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <RootNamespace>SimpleCaptchaDotNet</RootNamespace>
        <RepositoryUrl>https://github.com/Pasi4K5/simple-captcha-dot-net</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Version>1.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
      <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\*.ttf" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
